[#51] Update typography tokens
Orange-OpenSource/ouds-ios pull request #116
Opened 2024-09-20 12:59 UTC by pylapp

_Note: Please transform `- [ ]` into `- (NA)` in the description when things are not applicable_

### Related issues

#51

### Description

Add last tokens and unit tests

### Motivation & Context

### Types of change

- New feature (non-breaking change which adds functionality)

### Previews

### Checklist

#### Contribution

- [x] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/ouds-ios/blob/develop/.github/CONTRIBUTING.md)

#### Accessibility

-(NA) My change follows accessibility good practices

#### Design

-(NA) My change respects the design guidelines of _Orange Unified Design System_

#### Development

- [x] My change follows the [developer guide](https://github.com/Orange-OpenSource/ouds-ios/blob/develop/.github/DEVELOP.md)
- [x]  I have added unit tests to cover my changes _(optional)_

#### Documentation

- [x] My change introduces changes to the documentation and/or I have updated the documentation accordingly

### Checklist (for Core Team only)

- [x] The evolution have been tested and the project builds for iPhones and iPads
- [x] Code review has been done by reviewers according to [CODEOWNERS file](https://github.com/Orange-OpenSource/ouds-ios/blob/develop/.github/CODEOWNERS)
-(NA) Design review has been done
-(NA) Accessibiltiy review has been done
-(NA) Q/A team has tested the evolution
- [x] Documentation has been updated if relevant
- [x] Internal files have been updated if relevant (like CONTRIBUTING, DEVELOP, THIRD_PARTY, CONTRIBUTORS, NOTICE)
- [x] CHANGELOG has been updated respecting [keep a changelog rules](https://keepachangelog.com/en/1.0.0/) and reference the issues

2024-09-20 13:02 UTC, pylapp commented
@ludovic35 The commit message to use after the review and the merge (squash + merge commit) should be for example:

```
feat: add missing `letterSpacing` typography tokens (#51)
```

2024-09-20 13:12 UTC, ludovic35 requested changes

2024-09-20 13:12 UTC, ludovic35 commented on OUDS/Core/Tokens/RawTokens/Sources/Composites/TypographyRawTokens+Composites.swift
> +    /// Operator which will return true `true` if `lhs` is smaller than `rhs`.
remove one true

2024-09-23 07:57 UTC, ludovic35 approved these changes

2024-09-23 08:02 UTC, ludovic35 approved these changes

2024-09-23 08:04 UTC, ludovic35 approved these changes

2024-09-23 08:10 UTC, ludovic35 approved these changes

2024-09-23 09:13 UTC, pylapp reviewed
LGTM

2024-09-23 09:19 UTC, merged