[#157] On opacity screen, add a border around the view showing the opacity
Orange-OpenSource/ouds-ios pull request #162
Opened 2024-10-04 12:05 UTC by ludovic35

_Note: Please transform `- [ ]` into `- (NA)` in the description when things are not applicable_

### Related issues

### Description

### Motivation & Context

### Types of change

- Bug fix (non-breaking which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Refactoring (non-breaking change)
- Breaking change (fix or feature that would change existing functionality)

### Previews

### Checklist

#### Contribution

- [ ] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/ouds-ios/blob/develop/.github/CONTRIBUTING.md)

#### Accessibility

- [ ] My change follows accessibility good practices

#### Design

- [ ] My change respects the design guidelines of _Orange Unified Design System_

#### Development

- [ ] My change follows the [developer guide](https://github.com/Orange-OpenSource/ouds-ios/blob/develop/.github/DEVELOP.md)
- [ ]  I have added unit tests to cover my changes _(optional)_

#### Documentation

- [ ] My change introduces changes to the documentation and/or I have updated the documentation accordingly

### Checklist (for Core Team only)

- [ ] The evolution have been tested and the project builds for iPhones and iPads
- [ ] Code review has been done by reviewers according to [CODEOWNERS file](https://github.com/Orange-OpenSource/ouds-ios/blob/develop/.github/CODEOWNERS)
- [ ] Design review has been done
- [ ] Accessibiltiy review has been done
- [ ] Q/A team has tested the evolution
- [ ] Documentation has been updated if relevant
- [ ] Internal files have been updated if relevant (like CONTRIBUTING, DEVELOP, THIRD_PARTY, CONTRIBUTORS, NOTICE)
- [ ] CHANGELOG has been updated respecting [keep a changelog rules](https://keepachangelog.com/en/1.0.0/) and reference the issues

2024-10-04 22:12 UTC, pylapp approved these changes
LGTM

2024-10-04 22:14 UTC, pylapp requested changes

2024-10-04 22:14 UTC, pylapp commented on CHANGELOG.md
> +- [DemoApp] On opacity screen, add a border around the view showing the opacity ([#157](https://github.com/Orange-OpenSource/ouds-ios/issues/157))
Il faut que tu mettes à jour ta branche car le CHANGELOG n'est pas bon ; cette ligne est censée être dans la nouvelle section (unreleased) vierge de tout ajout aujourd'hui

2024-10-04 22:16 UTC, pylapp commented
@ludovic35 Si ta PR est prête à être relue, retire l'état "draft". J'ai été notifié que tu voulais une revue, donc je m'attends naturellement à ce que la PR ne soit pas en draft.

Il faut aussi que tu synchronises ta branche avec _develop_ qui a bougé depuis.

2024-10-07 07:27 UTC, ludovic35 commented
Etrange quelle ne sois pas en Draft car je n'ai pas terminé car il fallait faire le rebase en autre

2024-10-07 07:29 UTC, ludovic35 reviewed
Fixed

2024-10-07 11:03 UTC, pylapp requested changes

2024-10-07 11:03 UTC, pylapp commented on CHANGELOG.md
> +### Changed
Ca ne sert à rien d'ajouter des entrées vides, il faut que tu supprimes ces trois dernières sections.

2024-10-07 11:03 UTC, pylapp commented on OUDS/Core/Components/Sources/ViewModifiers/BorderModifiers/BorderModifier.swift
> +    private let colorSementic: ColorSemanticToken
Ca ne sert à rien d'avoir une variable qui porte son type, dans la mesure où son type est clair.
Il faut garder `color` ou alors prendre par exemple `asignedColor`, ici `colorSementic` n'apporte rien d"utile et en plus contient une typo ("semantic" plutôt que "sementic")

2024-10-07 12:14 UTC, ludovic35 commented on OUDS/Core/Components/Sources/ViewModifiers/BorderModifiers/BorderModifier.swift
> +    private let colorSementic: ColorSemanticToken
bah c'est pas une color c'est un sementic mais comme si tu veux...

2024-10-07 12:21 UTC, ludovic35 commented
(NA) Design review has been done
(NA) Accessibiltiy review has been done
(NA) Q/A team has tested the evolution

Marked as NA, but need to be done some time...

2024-10-07 12:51 UTC, pylapp approved these changes
LGTM

2024-10-07 12:52 UTC, merged