[#149] Add spacing screen in demo app
Orange-OpenSource/ouds-ios pull request #176
Opened 2024-10-07 13:36 UTC by ludovic35

_Note: Please transform `- [ ]` into `- (NA)` in the description when things are not applicable_

### Related issues

### Description

### Motivation & Context

### Types of change

- Bug fix (non-breaking which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Refactoring (non-breaking change)
- Breaking change (fix or feature that would change existing functionality)

### Previews

### Checklist

#### Contribution

- [ ] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/ouds-ios/blob/develop/.github/CONTRIBUTING.md)

#### Accessibility

- [ ] My change follows accessibility good practices

#### Design

- [ ] My change respects the design guidelines of _Orange Unified Design System_

#### Development

- [ ] My change follows the [developer guide](https://github.com/Orange-OpenSource/ouds-ios/blob/develop/.github/DEVELOP.md)
- [ ]  I have added unit tests to cover my changes _(optional)_

#### Documentation

- [ ] My change introduces changes to the documentation and/or I have updated the documentation accordingly

### Checklist (for Core Team only)

- [ ] The evolution have been tested and the project builds for iPhones and iPads
- [ ] Code review has been done by reviewers according to [CODEOWNERS file](https://github.com/Orange-OpenSource/ouds-ios/blob/develop/.github/CODEOWNERS)
- [ ] Design review has been done
- [ ] Accessibiltiy review has been done
- [ ] Q/A team has tested the evolution
- [ ] Documentation has been updated if relevant
- [ ] Internal files have been updated if relevant (like CONTRIBUTING, DEVELOP, THIRD_PARTY, CONTRIBUTORS, NOTICE)
- [ ] CHANGELOG has been updated respecting [keep a changelog rules](https://keepachangelog.com/en/1.0.0/) and reference the issues

2024-10-08 14:42 UTC, pylapp requested changes
Des petites choses à revoir :)

2024-10-08 14:42 UTC, pylapp commented on NOTICE.txt
> +./Showcase/Showcase/Resources/Assets.xcassets/Tokens/ic_dimension.imageset/ic_dimension.svg
Je note que le fichier s'appelle **ic_spacing.svg** , je pense que le fichier NOTICE n'est pas bon ou alors qu'il faut renommer le fichier

2024-10-08 14:42 UTC, pylapp commented on OUDS/Core/Tokens/SemanticTokens/Sources/Multiples/MultipleSpacingTokens.swift
> +    /// - Parameter userInterfaceSizeClass: The user interface size class (Could be horizontal or vertical)
Cette ligne
```swift
/// - Parameter userInterfaceSizeClass: The user interface size class (Could be horizontal or vertical)
```
n'est pas cohérente. Quand je lis le code, `UserInterfaceSizeClass` ne me semble pas avoir de valeur "horizontal" et "vertical".

2024-10-08 14:42 UTC, pylapp commented on Showcase/Showcase/Pages/Utils/ShowcaseVariantElement.swift
> +import SwiftUI
Les _imports_ ne sont pas ordonnés alphabétiquement

2024-10-08 15:02 UTC, ludovic35 commented on NOTICE.txt
> +./Showcase/Showcase/Resources/Assets.xcassets/Tokens/ic_dimension.imageset/ic_dimension.svg
oups

2024-10-08 15:04 UTC, ludovic35 commented on Showcase/Showcase/Pages/Utils/ShowcaseVariantElement.swift
> +import SwiftUI
swift lint ne la pas vu, étrange

2024-10-08 21:20 UTC, pylapp requested changes

2024-10-08 21:20 UTC, pylapp commented on OUDS/Core/Tokens/SemanticTokens/Sources/Multiples/MultipleSpacingTokens.swift
> +        userInterfaceSizeClass == .compact ? compact : regular
Comment ça peut compiler ? Je n'ai pas testé mais si j'en crois la doc (https://developer.apple.com/documentation/swiftui/userinterfacesizeclass) `UserInterfaceSizeClass` n'a pas de valeur _compact_

2024-10-08 21:20 UTC, pylapp commented on Showcase/Showcase/Pages/Utils/ShowcaseVariantElement.swift
> +    init(elements: [ShowcaseElement]) {
L'init ne sert à rien ici, il faut l'enlever

2024-10-09 15:36 UTC, pylapp approved these changes
LGTM

2024-10-09 15:37 UTC, merged