154 demo app add more UI tests on demo app
Orange-OpenSource/ouds-ios pull request #197
Opened 2024-10-16 11:46 UTC by Tayebsed93

_Note: Please transform `- [ ]` into `- (NA)` in the description when things are not applicable_

### Related issues

### Description

### Motivation & Context

### Types of change

- Bug fix (non-breaking which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Refactoring (non-breaking change)
- Breaking change (fix or feature that would change existing functionality)

### Previews

### Checklist

#### Contribution

- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/ouds-ios/blob/develop/.github/CONTRIBUTING.md)

#### Accessibility

- [NA] My change follows accessibility good practices

#### Design

- [NA] My change respects the design guidelines of _Orange Unified Design System_

#### Development

- [X] My change follows the [developer guide](https://github.com/Orange-OpenSource/ouds-ios/blob/develop/.github/DEVELOP.md)
- [X] I checked my changes do not add new SwiftLint warnings
- [X]  I have added unit tests to cover my changes _(optional)_

#### Documentation

- [NA] My change introduces changes to the documentation and/or I have updated the documentation accordingly

### Checklist (for Core Team only)

- [ ] The evolution have been tested and the project builds for iPhones and iPads
- [ ] Code review has been done by reviewers according to [CODEOWNERS file](https://github.com/Orange-OpenSource/ouds-ios/blob/develop/.github/CODEOWNERS)
- [ ] Design review has been done
- [ ] Accessibiltiy review has been done
- [ ] Q/A team has tested the evolution
- [ ] Documentation has been updated if relevant
- [ ] Internal files have been updated if relevant (like CONTRIBUTING, DEVELOP, THIRD_PARTY, CONTRIBUTORS, NOTICE)
- [ ] CHANGELOG has been updated respecting [keep a changelog rules](https://keepachangelog.com/en/1.0.0/) and reference the issues

2024-10-17 13:29 UTC, pylapp commented
@Tayebsed93  Ça ne va pas du tout, j'ai remis ta PR en _draft_, elle n'est pas en état d'être relue.
J'ai plus de 250 warnings, ta branche n'était pas rebasée, et je ne comprends pas pourquoi c'est `BorderTokenPage` qui est utilisé dans les fonctions de tests qui ne concernent pas les _borders_ (e.g. _typography_, _elevation_)

2024-10-17 15:46 UTC, Tayebsed93 commented
@pylapp Merci pour ton retour. Désormais, j'arrive à voir les warnings et plus de 250 d'entre eux sont corrigés. Les fonctions de test ont aussi été modifiées. Le rebase est fait

2024-10-17 20:26 UTC, pylapp requested changes
La PR est loin d'être acceptable en l'état.

Il ne faut pas que tu corriges bêtement les _warnings_ sans faire attention à ce que tu fais, surtout quand tu apportes de l'incohérence entre les fichiers du projet.

Regarde des classes de tests à côté ; tu pourras grandement t'en inspirer.

Dans les points à corriger : 
1.  Il faut des sauts de lignes entre les fonctions, c'est la base ;
2. le warning que tu as voulu corriger ne te dit pas de supprimer la ligne, mais les espaces inutiles en début de ligne ;
3. Pour les classes de tests on n'a pas besoin de deinit, pour le coup tu peux désactiver proprement ce warning comme indiqué en commentaire ;
4. Tu as réussi à mettre des fonctions de tests en dehors de leur classe de test
5. On ajout les nouvelles lignes du CHANGELOG par le haut ; ta ligne est totalement perdue dans une section
6. Aucune documentation, tant pour les classes de tests que dans le DEVELOP par exemple
7. Les MARKS sont utilisés n'importe comment
8. Pourquoi on ne teste parfois que pour le _color scheme_ light et pas le dark aussi ?

Un MARK est une balise qui sert d'ancrage dans la minimap de Xcode, je te laisse chercher. Si tu ajoute après les : un tiret, une ligne horizontale apparait pour séparer visuellement les choses. L'intérêt des MARK est d'apporter une aide visuelle dans le code, avec une structure claire. Deux MARK qui se suivent ne servent à rien.

Par exemple, si je prends :
```swift
    // MARK: - Tests
    // MARK: - Orange Theme Light Mode Width Tests
    // MARK: - Width Tokens Tests
```
Le seul MARK utile est ici : 
```swift
    // MARK: - Orange Theme Light Mode Width Tests
```

D'ailleurs, je ne comprends pas comment pour un même code modulo la valeur du paramètre "named" tu peux définir des cas de tests différents.
Il faudrait que tu précises à la fin de la rubrique "UI tests in demo app" de DEVELOP comment ça fonctionne. Si je ne comprends pas, d'autres ne comprendront pas. Si on doit te demander comment ça fonctionne, c'est qu'il y a un problème _a minima_ de documentation quelque part. Si tu n'es pas à l'aise en anglais pour expliquer clairement comment ça fonctionne, rédige le paragraphe en français en commentaire de cette PR et je traduirais.

Au besoin, demande de l'aide à @ludovic35  qui avait travaillé sur le sujet.

2024-10-17 20:26 UTC, pylapp commented on Showcase/Showcase/Pages/ThemeSelection/ThemeSelection.swift
> +                .accessibilityLabel("app_common_theme_image_a11y")
Que fait cette ligne de code ici ? Je ne vois pas le rapport avec les tests UI que tu implémentes. Si ça n'a pas de rapport, il faut retirer. Si tu as décelé un bug, il faut créer une _issue_.

2024-10-17 20:26 UTC, pylapp commented on Showcase/Showcase/Pages/Utils/ShowcaseElementsPage.swift
> +                            .accessibilityLabel(element.id)
D'où vient cette ligne de code ? Si ça n'a pas de rapport avec le but initial de ta PR il faut retirer. Si tu as décelé un bug, il faut faire une _issue_

2024-10-17 20:26 UTC, pylapp commented on Showcase/Showcase/Resources/en.lproj/Localizable.strings
> +// MARK: - Common
D'où vient cette ligne de code ? Si ça n'a pas de rapport avec le but initial de ta PR il faut retirer. Si tu as décelé un bug, il faut faire une _issue_

Par ailleurs, il faut un saut de ligne après le MARK, comme c'est le cas ailleurs dans le fichier.

2024-10-17 20:26 UTC, pylapp commented on Showcase/ShowcaseTests/OUDSComponentsUITests/OUDSComponentsUITests.swift
> +import SwiftUI
Pourquoi faire deux blocs d'imports ? Inspire toi des autres classes de tests. Il faut que tu mettes tout d'un bloc, trié alphabétiquement.

2024-10-17 20:26 UTC, pylapp commented on Showcase/ShowcaseTests/OUDSComponentsUITests/OUDSComponentsUITests.swift
> +class OUDSComponentsUITests: XCTestCase {
Il est superflu d'avoir un *deinit* dans les classes de tests ; regarde les autres fichiers de tests. Il y a une règle pour désactiver le warning associé : désactive-le au début de fichier, active-le à la fin, comme c'est le cas pour les autres fichiers.

Une classe doit être _final_, ajoute le mot clé.

Les "MARK: - Tests" n'apportent aucune valeur ici ; tu as déjà des MARK qui donnent des points d'ancrage dans la _minimap_, avec un trait horizontal dans l'affichage du code source.

De puis, il faut des sauts de lignes après les MARK, et entre les fonctions.
Les warnings que tu as certainement voulu corriger ne te demandaient pas de supprimer les lignes, mais de supprimes des espaces en trop en début de ligne.

Inspire toi des autres classe de test ; tu n'as même pas de documentation qui décrit le but de ce fichier.

2024-10-17 20:26 UTC, pylapp commented on Showcase/ShowcaseTests/OUDSTokensBorderUITests/OUDSTokensBorderUITests.swift
> +class OUDSTokensBorderUITests: XCTestCase {
Il est superflu d'avoir un *deinit* dans les classes de tests ; regarde les autres fichiers de tests. Il y a une règle pour désactiver le warning associé : désactive-le au début de fichier, active-le à la fin, comme c'est le cas pour les autres fichiers.

Une classe doit être _final_, ajoute le mot clé.

Les "MARK: - Tests" n'apportent aucune valeur ici ; tu as déjà des MARK qui donnent des points d'ancrage dans la _minimap_, avec un trait horizontal dans l'affichage du code source.

De puis, il faut des sauts de lignes après les MARK, et entre les fonctions.
Les warnings que tu as certainement voulu corriger ne te demandaient pas de supprimer les lignes, mais de supprimes des espaces en trop en début de ligne.

Inspire toi des autres classe de test ; tu n'as même pas de documentation qui décrit le but de ce fichier.

Tu doubles à chaque fois tes MARK, ça ne sert à rien. Fais en un utile plutôt que deux qui se parasitent.

2024-10-17 20:26 UTC, pylapp commented on Showcase/ShowcaseTests/OUDSTokensBorderUITests/OUDSTokensBorderUITests.swift
> +func testBorderToken_InverseTheme_SectionRadius_BorderRadiusNone_Light() {
Pourquoi ces fonctions ne sont pas dans la classe de tests ? Elles doivent impérativement y être.

2024-10-17 20:26 UTC, pylapp commented on Showcase/ShowcaseTests/OUDSTokensBorderUITests/OUDSTokensBorderUITests.swift
> +func testBorderToken_InverseTheme_SectionRadius_BorderRadiusDefault_Light() {
Reste cohérent avec les autres fichiers du projet ; met des sauts de ligne entre les fonctions ! Configure au besoin ton IDE pour pas qu'il ajoute des espaces inutilement.

2024-10-17 20:26 UTC, pylapp commented on Showcase/ShowcaseTests/OUDSTokensDimensionUITests/OUDSTokensDimensionUITests.swift
> +class OUDSTokensDimensionUITests: XCTestCase {
Il est superflu d'avoir un *deinit* dans les classes de tests ; regarde les autres fichiers de tests. Il y a une règle pour désactiver le warning associé : désactive-le au début de fichier, active-le à la fin, comme c'est le cas pour les autres fichiers.

Une classe doit être _final_, ajoute le mot clé.

Les "MARK: - Tests" n'apportent aucune valeur ici ; tu as déjà des MARK qui donnent des points d'ancrage dans la _minimap_, avec un trait horizontal dans l'affichage du code source.

De puis, il faut des sauts de lignes après les MARK, et entre les fonctions.
Les warnings que tu as certainement voulu corriger ne te demandaient pas de supprimer les lignes, mais de supprimes des espaces en trop en début de ligne.

Inspire toi des autres classe de test ; tu n'as même pas de documentation qui décrit le but de ce fichier.

Tu doubles à chaque fois tes MARK, ça ne sert à rien. Fais en un utile plutôt que deux qui se parasitent.

2024-10-17 20:26 UTC, pylapp commented on Showcase/ShowcaseTests/OUDSTokensElevationUITests/OUDSTokensElevationUITests.swift
> +class OUDSTokensElevationUITests: XCTestCase {
Il est superflu d'avoir un *deinit* dans les classes de tests ; regarde les autres fichiers de tests. Il y a une règle pour désactiver le warning associé : désactive-le au début de fichier, active-le à la fin, comme c'est le cas pour les autres fichiers.

Une classe doit être _final_, ajoute le mot clé.

Les "MARK: - Tests" n'apportent aucune valeur ici ; tu as déjà des MARK qui donnent des points d'ancrage dans la _minimap_, avec un trait horizontal dans l'affichage du code source.

De puis, il faut des sauts de lignes après les MARK, et entre les fonctions.
Les warnings que tu as certainement voulu corriger ne te demandaient pas de supprimer les lignes, mais de supprimes des espaces en trop en début de ligne.

Inspire toi des autres classe de test ; tu n'as même pas de documentation qui décrit le but de ce fichier.

Tu doubles à chaque fois tes MARK, ça ne sert à rien. Fais en un utile plutôt que deux qui se parasitent.

2024-10-17 20:26 UTC, pylapp commented on Showcase/ShowcaseTests/OUDSTokensOpacityUITests/OUDSTokensOpacityUITests.swift
> +class OUDSTokensOpacityUITests: XCTestCase {
Il est superflu d'avoir un *deinit* dans les classes de tests ; regarde les autres fichiers de tests. Il y a une règle pour désactiver le warning associé : désactive-le au début de fichier, active-le à la fin, comme c'est le cas pour les autres fichiers.

Une classe doit être _final_, ajoute le mot clé.

Les "MARK: - Tests" n'apportent aucune valeur ici ; tu as déjà des MARK qui donnent des points d'ancrage dans la _minimap_, avec un trait horizontal dans l'affichage du code source.

De puis, il faut des sauts de lignes après les MARK, et entre les fonctions.
Les warnings que tu as certainement voulu corriger ne te demandaient pas de supprimer les lignes, mais de supprimes des espaces en trop en début de ligne.

Inspire toi des autres classe de test ; tu n'as même pas de documentation qui décrit le but de ce fichier.

Tu doubles à chaque fois tes MARK, ça ne sert à rien. Fais en un utile plutôt que deux qui se parasitent.

2024-10-17 20:26 UTC, pylapp commented on Showcase/ShowcaseTests/OUDSTokensTypographyUITests/OUDSTokensTypographyUITests.swift
> +class OUDSTokensTypographyUITests: XCTestCase {
Il est superflu d'avoir un *deinit* dans les classes de tests ; regarde les autres fichiers de tests. Il y a une règle pour désactiver le warning associé : désactive-le au début de fichier, active-le à la fin, comme c'est le cas pour les autres fichiers.

Une classe doit être _final_, ajoute le mot clé.

Les "MARK: - Tests" n'apportent aucune valeur ici ; tu as déjà des MARK qui donnent des points d'ancrage dans la _minimap_, avec un trait horizontal dans l'affichage du code source.

De puis, il faut des sauts de lignes après les MARK, et entre les fonctions.
Les warnings que tu as certainement voulu corriger ne te demandaient pas de supprimer les lignes, mais de supprimes des espaces en trop en début de ligne.

Inspire toi des autres classe de test ; tu n'as même pas de documentation qui décrit le but de ce fichier.

Tu doubles à chaque fois tes MARK, ça ne sert à rien. Fais en un utile plutôt que deux qui se parasitent.

2024-11-07 08:27 UTC, ludovic35 requested changes

2024-11-07 08:27 UTC, ludovic35 commented on Showcase/Showcase/Pages/Tokens/Border/BorderTokenPage.swift
> +        /// Move activeColorScheme here to ensure colorScheme is accessible (for UI tests purposes)
to avoid to variable local variable prefer create a computed variable

2024-11-18 14:06 UTC, pylapp requested changes
Actions à prendre : 
- remplacer les **///** qui sont **dans** les fonctions par tes **//** ;
- pas de saut de ligne vides entre la doc et l'en-tête de tes *class* de tests
- certains éléments sont *public* alors que pas besoin
- certaines *property* ne sont pas documentées (*size class*, *color scheme*)
- le DEVELOP un peu à revoir
- 
Mais on tient le bon bout !

2024-11-18 14:06 UTC, pylapp commented on Showcase/ShowcaseTests/__Snapshots__/OUDSTokensDimensionUITests/Size/OUDSTokensSizeUITests.swift
> +/// To ensure the TokensSize are tested for UI compatibility with the reference image recorded
Pour chacune de tes fonctions, remplace les **///** par tes **//**.
Les **///** ne doivent servir qu'à commenter / documenter des fonctions / variables etc via leur déclarations.
Quand c'est "dedans" c'est du double slash.

Et supprime cette ligne vide inutile entre la doc et le début de ta *class*.

2024-11-18 14:06 UTC, pylapp commented on Showcase/ShowcaseTests/__Snapshots__/OUDSTokensColorUITests/OUDSTokensColorUITests.swift
> +
Pour chacune de tes fonctions, remplace les **///** par tes **//**.
Les **///** ne doivent servir qu'à commenter / documenter des fonctions / variables etc via leur déclarations.
Quand c'est "dedans" c'est du double slash.

Et supprime cette ligne vide inutile entre la doc et le début de ta *class*.

2024-11-18 14:06 UTC, pylapp commented on Showcase/ShowcaseTests/__Snapshots__/OUDSTokensDimensionUITests/Space/OUDSTokensSpaceUITests.swift
> +
Pour chacune de tes fonctions, remplace les **///** par tes **//**.
Les **///** ne doivent servir qu'à commenter / documenter des fonctions / variables etc via leur déclarations.
Quand c'est "dedans" c'est du double slash.

Et supprime cette ligne vide inutile entre la doc et le début de ta *class*.

2024-11-18 14:06 UTC, pylapp commented on Showcase/ShowcaseTests/__Snapshots__/OUDSTokensElevationUITests/OUDSTokensElevationUITests.swift
> +
Pour chacune de tes fonctions, remplace les **///** par tes **//**.
Les **///** ne doivent servir qu'à commenter / documenter des fonctions / variables etc via leur déclarations.
Quand c'est "dedans" c'est du double slash.

Et supprime cette ligne vide inutile entre la doc et le début de ta *class*.

2024-11-18 14:06 UTC, pylapp commented on Showcase/ShowcaseTests/__Snapshots__/OUDSTokensOpacityUITests/OUDSTokensOpacityUITests.swift
> +
Pour chacune de tes fonctions, remplace les **///** par tes **//**.
Les **///** ne doivent servir qu'à commenter / documenter des fonctions / variables etc via leur déclarations.
Quand c'est "dedans" c'est du double slash.

Et supprime cette ligne vide inutile entre la doc et le début de ta *class*.

2024-11-18 14:06 UTC, pylapp commented on Showcase/ShowcaseTests/__Snapshots__/OUDSTokensTypographyUITests/OUDSTypographyUITests.swift
> +
Pour chacune de tes fonctions, remplace les **///** par tes **//**.
Les **///** ne doivent servir qu'à commenter / documenter des fonctions / variables etc via leur déclarations.
Quand c'est "dedans" c'est du double slash.

Et supprime cette ligne vide inutile entre la doc et le début de ta *class*.

2024-11-20 10:21 UTC, merged