Token code example
Orange-OpenSource/ouds-ios pull request #297
Opened 2024-11-19 10:08 UTC by Tayebsed93

_Note: Please transform `- [ ]` into `- (NA)` in the description when things are not applicable_

### Related issues

### Description

### Motivation & Context

### Types of change

- Bug fix (non-breaking which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Refactoring (non-breaking change)
- Breaking change (fix or feature that would change existing functionality)

### Previews

### Checklist

#### Contribution

- [ ] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/ouds-ios/blob/develop/.github/CONTRIBUTING.md)

#### Accessibility

- [ ] My change follows accessibility good practices

#### Design

- [ ] My change respects the design guidelines of _Orange Unified Design System_

#### Development

- [ ] My change follows the [developer guide](https://github.com/Orange-OpenSource/ouds-ios/blob/develop/.github/DEVELOP.md)
- [ ] I checked my changes do not add new SwiftLint warnings
- [ ]  I have added unit tests to cover my changes _(optional)_

#### Documentation

- [ ] My change introduces changes to the documentation and/or I have updated the documentation accordingly

### Checklist (for Core Team only)

- [ ] The evolution have been tested and the project builds for iPhones and iPads
- [ ] Code review has been done by reviewers according to [CODEOWNERS file](https://github.com/Orange-OpenSource/ouds-ios/blob/develop/.github/CODEOWNERS)
- [ ] Design review has been done
- [ ] Accessibiltiy review has been done
- [ ] Q/A team has tested the evolution
- [ ] Documentation has been updated if relevant
- [ ] Internal files have been updated if relevant (like CONTRIBUTING, DEVELOP, THIRD_PARTY, CONTRIBUTORS, NOTICE)
- [ ] CHANGELOG has been updated respecting [keep a changelog rules](https://keepachangelog.com/en/1.0.0/) and reference the issues
- [ ]  [The wiki](https://github.com/Orange-OpenSource/ouds-ios/wiki) has been updated if needed _(optional)_

2024-11-21 14:25 UTC, pylapp requested changes
Il faut que tu corriges le CHANGELOG et le NOTICE.txt entre autres.

2024-11-21 14:25 UTC, pylapp commented on NOTICE.txt
> +./Showcase/Showcase/Resources/Assets.xcassets/Tokens/ic_chevron-down.imageset/ic_chevron-down.svg
Les fichiers que tu mentionnes n'existent pas. Soit tu les renommes, soit tu changes ces lignes dans le NOTICE.txt

Au dernier commit relu (c510bcb1a27f5f6840809344e6670d370a703908), j'ai les fichiers suivants : 
- form-chevron-down.png
- form-chevron-up.png
- ic_copy.png

Au lieu de : 
- ic_chevron-down.svg
- ic_chevron-upsvg
- ic_copy.svg

Normalement tu es censé s'avoir quels sont les fichiers que tu ajoutes, surtout que ton outil graphique gérant Git affiche les fichiers complets et que tu peux fouiller les dossiers _a minima_ avec le _Finder_

2024-11-21 14:25 UTC, pylapp commented on Showcase/Showcase/Pages/Tokens/Dimension/Space/SpaceTokenPage.swift
> +            // Show token code
Reste cohérent avec les autres `Page`; si pour les modifications que tu apportes tu n'as pas mis de commentaires, n'en met pas non plus ici.

2024-11-21 14:25 UTC, pylapp commented on Showcase/Showcase/Pages/Utils/ShowcaseTokenCode.swift
> +    // MARK: Stored Properties
Tu peux je pense supprimer cette ligne.

2024-11-21 15:06 UTC, pylapp submitted a review, later dismissed
LGTM

2024-11-25 13:41 UTC, pylapp requested changes
J'ai fait plusieurs fois la même remarque au sujet d'une variable que tu créés juste pour l'utiliser une seule fois juste après ; je me demande si tu ne peux pas simplement ne pas l'utiliser et passer sa valeur dans ta vue.

2024-11-25 13:41 UTC, pylapp commented on Showcase/Showcase/Pages/Tokens/Border/BorderTokenPage.swift
> +                    let tokenCode = "theme.borderWidthDefault"
Pourquoi stocker la valeur dans une variable `tokenCode` alors que tu pourrais la passer directement dans ton objet `ShowcaseTokenCode` ? Je ne vois pas l'intérêt de stocker dans une variable.

2024-11-25 13:41 UTC, pylapp commented on Showcase/Showcase/Pages/Tokens/Color/ColorTokenPage.swift
> +                let tokenCode = "theme.colorBgPrimary.color(for: colorScheme)"
Pourquoi stocker la valeur dans une variable `tokenCode` alors que tu pourrais la passer directement dans ton objet `ShowcaseTokenCode` ? Je ne vois pas l'intérêt de stocker dans une variable.

2024-11-25 13:41 UTC, pylapp commented on Showcase/Showcase/Pages/Tokens/Dimension/Size/SizeTokenPage.swift
> +                let tokenCode = "theme.sizeIconWithHeadingXLargeShort.dimension(for: horizontalSizeClass ?? .regular)"
Pourquoi stocker la valeur dans une variable `tokenCode` alors que tu pourrais la passer directement dans ton objet `ShowcaseTokenCode` ? Je ne vois pas l'intérêt de stocker dans une variable.

2024-11-25 13:41 UTC, pylapp commented on Showcase/Showcase/Pages/Tokens/Dimension/Space/SpaceTokenPage.swift
> +            Section {
Pourquoi stocker la valeur dans une variable `tokenCode` alors que tu pourrais la passer directement dans ton objet `ShowcaseTokenCode` ? Je ne vois pas l'intérêt de stocker dans une variable.

2024-11-25 13:41 UTC, pylapp commented on Showcase/Showcase/Pages/Tokens/Elevation/ElevationTokenPage.swift
> +                let tokenCode = "theme.elevationNone.elevation(for: colorScheme)"
Pourquoi stocker la valeur dans une variable `tokenCode` alors que tu pourrais la passer directement dans ton objet `ShowcaseTokenCode` ? Je ne vois pas l'intérêt de stocker dans une variable.

2024-11-25 13:41 UTC, pylapp commented on Showcase/Showcase/Pages/Tokens/Grid/GrisTokenPage.swift
> +                let tokenCode = "theme.gridColumnCount(for: horizontalSizeClass)"
Pourquoi stocker la valeur dans une variable `tokenCode` alors que tu pourrais la passer directement dans ton objet `ShowcaseTokenCode` ? Je ne vois pas l'intérêt de stocker dans une variable.

2024-11-25 13:41 UTC, pylapp commented on Showcase/Showcase/Pages/Tokens/Opacity/OpacityTokenPage.swift
> +                let tokenCode = "theme.opacityTransparent"
Pourquoi stocker la valeur dans une variable `tokenCode` alors que tu pourrais la passer directement dans ton objet `ShowcaseTokenCode` ? Je ne vois pas l'intérêt de stocker dans une variable.

2024-11-25 13:41 UTC, pylapp commented on Showcase/Showcase/Pages/Tokens/Typography/TypographyTokenPage.swift
> +                let tokenCode = "theme.typeBodyStrongLarge(theme)"
Pourquoi stocker la valeur dans une variable `tokenCode` alors que tu pourrais la passer directement dans ton objet `ShowcaseTokenCode` ? Je ne vois pas l'intérêt de stocker dans une variable.

2024-11-27 16:23 UTC, ludovic35 commented
@pylapp  Need to review last commit

2024-11-29 09:41 UTC, pylapp approved these changes
LGTM (after some fixes / refactoring from my side)

2024-11-29 09:53 UTC, merged