[#29] Add raw tokens and semantic tokens for opacity
Orange-OpenSource/ouds-ios pull request #61
Opened 2024-08-06 07:38 UTC by pylapp

THis commit updates when needed the values of raw tokens and semenatic tokens for opacity. It brings also unit tests for theme overriding and raw tokens relationships.

_Note: Please transform `- [ ]` into `- (NA)` in the description when things are not applicable_

### Related issues

#29

### Description

Update raw and semantic tokens for opacity

### Motivation & Context

See #29

### Types of change

- New feature (non-breaking change which adds functionality)

### Previews

### Checklist

#### Contribution

- [x] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/ouds-ios/blob/develop/.github/CONTRIBUTING.md)

#### Accessibility

- (NA) My change follows accessibility good practices

#### Design

- (NA) My change respects the design guidelines of _Orange Unified Design System_

#### Development

- [x] My change follows the [developer guide](https://github.com/Orange-OpenSource/ouds-ios/blob/develop/.github/DEVELOP.md)
- [x]  I have added unit tests to cover my changes _(optional)_

#### Documentation

- [x] My change introduces changes to the documentation and/or I have updated the documentation accordingly

### Checklist (for Core Team only)

- (NA) The evolution have been tested and the project builds for iPhones and iPads
- [ ] Code review has been done by reviewers according to [CODEOWNERS file](https://github.com/Orange-OpenSource/ouds-ios/blob/develop/.github/CODEOWNERS)
- (NA) Design review has been done
- (NA) Accessibiltiy review has been done
- (NA) Q/A team has tested the evolution
- [x] Documentation has been updated if relevant
- (NA) Internal files have been updated if relevant (like CONTRIBUTING, DEVELOP, THIRD_PARTY, CONTRIBUTORS, NOTICE)
- [x] CHANGELOG has been updated respecting [keep a changelog rules](https://keepachangelog.com/en/1.0.0/) and reference the issues

2024-08-06 13:51 UTC, ludovic35 requested changes

2024-08-06 13:51 UTC, ludovic35 commented on OUDS/Core/Tokens/RawTokens/Sources/OpacityRawTokens.swift
>  public struct OpacityRawTokens {
use enum here 
and update comment

2024-08-06 17:01 UTC, pylapp commented on OUDS/Core/Tokens/RawTokens/Sources/OpacityRawTokens.swift
>  public struct OpacityRawTokens {
Resolved with rebase

2024-08-07 09:21 UTC, ludovic35 submitted a review, later dismissed

2024-08-07 14:23 UTC, merged